In [2]:
import numpy as np

In [3]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [4]:
x.dot(y)
#matrix multiplication

array([[ 28.,  64.],
       [ 67., 181.]])

In [5]:
np.dot(x,y)
#same

array([[ 28.,  64.],
       [ 67., 181.]])

In [6]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [7]:
x @ np.ones(3) # same as above

array([ 6., 15.])

In [8]:
from numpy.linalg import inv, qr

In [9]:
X = np.random.randn(5, 5)
mat = X.T.dot(X) #=det(X)*X
inv(mat)#inverse the matrix

array([[ 0.55661148,  0.25543972, -0.59754235,  0.21751446,  0.21246912],
       [ 0.25543972,  0.81449401,  0.36839231,  0.28533547,  0.17752539],
       [-0.59754235,  0.36839231,  2.95510264, -0.17294779, -0.0949499 ],
       [ 0.21751446,  0.28533547, -0.17294779,  0.60123936,  0.33936549],
       [ 0.21246912,  0.17752539, -0.0949499 ,  0.33936549,  0.48075832]])

In [10]:
q, r = qr(mat)