In [1]:
import numpy as np

In [2]:
arr = np.random.randn(5, 4)
arr

array([[-0.17664411,  0.31270058, -0.83702229, -2.93159129],
       [-0.92685643,  0.62594303,  0.81372737,  1.26380454],
       [-0.43081504, -0.39554313,  2.19351176, -0.27240937],
       [ 2.07674277,  0.12912749, -0.07133277, -0.07372644],
       [ 0.96484259,  0.07072312,  0.17817068,  0.30519281]])

In [3]:
arr.mean()

0.14092729409668261

In [4]:
np.mean(arr)

0.14092729409668261

In [5]:
arr.sum()

2.818545881933652

In [6]:
arr.mean(axis=1)

array([-0.90813928,  0.44415463,  0.27368606,  0.51520276,  0.3797323 ])

In [7]:
arr.sum(0)#means sum down the rows
arr.sum(1)#means sum across cols 

array([ 1.50726978,  0.7429511 ,  2.27705475, -1.70872975])

In [8]:
arr.cumsum(axis=0) #accumulation func.(running sum)

array([[-0.17664411,  0.31270058, -0.83702229, -2.93159129],
       [-1.10350054,  0.93864362, -0.02329493, -1.66778675],
       [-1.53431558,  0.54310049,  2.17021684, -1.94019612],
       [ 0.54242719,  0.67222798,  2.09888406, -2.01392256],
       [ 1.50726978,  0.7429511 ,  2.27705475, -1.70872975]])

In [9]:
arr.cumprod(axis=1)# accumulative (running product)

array([[-1.76644107e-01, -5.52367153e-02,  4.62343621e-02,
        -1.35540253e-01],
       [-9.26856431e-01, -5.80159326e-01, -4.72091520e-01,
        -5.96631407e-01],
       [-4.30815038e-01,  1.70405926e-01,  3.73787404e-01,
        -1.01823192e-01],
       [ 2.07674277e+00,  2.68164584e-01, -1.91289235e-02,
         1.41030752e-03],
       [ 9.64842590e-01,  6.82366762e-02,  1.21577753e-02,
         3.71046564e-03]])