In [18]:
import numpy as np

In [19]:
arr = np.arange(5)
arr * 4

array([ 0,  4,  8, 12, 16])

In [20]:
arr = np.random.randn(4, 3)
arr.mean(0)

array([ 0.17642226,  0.68846272, -0.2516646 ])

In [21]:
demeaned = arr - arr.mean(0)
demeaned

array([[-0.12789157,  0.21005988, -0.35167999],
       [-0.12327239, -0.80040197, -0.05122275],
       [ 0.30108617,  0.51627225, -1.17560304],
       [-0.04992221,  0.07406984,  1.57850578]])

In [22]:
demeaned.mean(0)

array([-1.38777878e-17, -2.77555756e-17,  0.00000000e+00])

In [23]:
arr

array([[ 0.04853069,  0.8985226 , -0.60334459],
       [ 0.05314987, -0.11193925, -0.30288736],
       [ 0.47750842,  1.20473497, -1.42726765],
       [ 0.12650005,  0.76253256,  1.32684118]])

In [24]:
row_means = arr.mean(1)
row_means

array([ 0.11456957, -0.12055891,  0.08499192,  0.7386246 ])

In [25]:
row_means.shape

(4,)

In [26]:
row_means.reshape((4, 1))

array([[ 0.11456957],
       [-0.12055891],
       [ 0.08499192],
       [ 0.7386246 ]])

In [27]:
demeaned = arr - row_means.reshape((4, 1))
demeaned.mean(1)

array([3.70074342e-17, 9.25185854e-18, 7.40148683e-17, 3.70074342e-17])

In [28]:
arr - arr.mean(1).reshape((4, 1))

array([[-0.06603888,  0.78395304, -0.71791416],
       [ 0.17370878,  0.00861966, -0.18232844],
       [ 0.39251651,  1.11974306, -1.51225956],
       [-0.61212455,  0.02390796,  0.58821658]])

In [29]:
arr = np.zeros((4, 4))
arr_3d = arr[:, np.newaxis, :]
arr_3d.shape

(4, 1, 4)

In [30]:
arr_1d = np.random.normal(size=3)
arr_1d[:, np.newaxis]


array([[-0.93850709],
       [ 1.07249994],
       [-0.0054285 ]])

In [31]:
arr_1d[np.newaxis, :]

array([[-0.93850709,  1.07249994, -0.0054285 ]])

In [33]:
arr = np.random.randn(3, 4, 5)
arr

array([[[ 0.06699418,  0.24466671, -0.68065827,  1.15327275,
          0.7161559 ],
        [ 0.50790045, -1.61774039, -0.09480188,  0.04255228,
          1.38179325],
        [ 0.04726939, -1.60759247, -0.6545497 ,  0.8017422 ,
          0.55499259],
        [ 0.03994892,  0.19977303,  0.95823461, -0.47344362,
          0.83284375]],

       [[-0.81710925, -0.5541517 , -0.32272192, -0.05081342,
         -0.62668063],
        [ 0.14820263,  0.83475931,  0.93913391,  0.34272322,
         -0.08186135],
        [ 1.62570277,  2.37077877,  0.31969213, -3.08712621,
         -1.20650386],
        [-0.60156316,  1.45385584, -0.89830313, -0.60378988,
         -1.50573821]],

       [[-1.14114768,  1.55760598, -0.06276899, -0.21489864,
          0.06192285],
        [-0.8751561 ,  0.24421921,  1.28982754,  1.23238678,
         -0.87384985],
        [-0.11333827,  1.76089822,  1.50157398,  2.20438979,
          0.35356793],
        [ 0.05594738, -0.1648587 , -1.3916535 ,  2.08026321,
         -0

In [34]:
depth_means = arr.mean(2)
depth_means

array([[ 0.30008626,  0.04394074, -0.1716276 ,  0.31147134],
       [-0.47429538,  0.43659155,  0.00450872, -0.43110771],
       [ 0.04014271,  0.20348552,  1.14141833,  0.00373879]])

In [35]:
demeaned = arr - depth_means[:, :, np.newaxis]
demeaned.mean(2)

array([[-4.44089210e-17,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-4.44089210e-17,  0.00000000e+00,  4.44089210e-17,
        -4.44089210e-17],
       [ 6.93889390e-18, -4.44089210e-17, -6.66133815e-17,
         4.44089210e-17]])

In [36]:
arr = np.zeros((4, 3))
arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [39]:
np.array([1.28, -0.42, 0.44, 1.6])
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 5.   ,  5.   ,  5.   ],
       [ 5.   ,  5.   ,  5.   ]])

In [40]:
arr[:2] = [[-1.37], [0.509]]
In [114]: arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 5.   ,  5.   ,  5.   ],
       [ 5.   ,  5.   ,  5.   ]])