In [2]:
import numpy as np

In [12]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:

old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d[0]


array([[42, 42, 42],
       [42, 42, 42]])

In [15]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
arr3d[1, 0]

array([7, 8, 9])

In [19]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [20]:
x[0]

array([7, 8, 9])