In [7]:
#indexing with slices
import numpy as np

In [8]:
arr = np.array([ 0, 1, 2, 3, 4, 64, 64, 64, 8, 9])
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [9]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [10]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [13]:
arr2d[1, :2]


array([4, 5])

In [14]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [15]:
#assigning to a slice expression assigns to the whole selection:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])