In [15]:
import numpy as np
arr = np.arange(10) 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[5]

5

In [17]:
arr[5:8]

array([5, 6, 7])

In [18]:
#broadcasting
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [19]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [20]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [21]:
#assign to all values in the array # arr will also change
arr_slice[:]=65
arr

array([ 0,  1,  2,  3,  4, 65, 65, 65,  8,  9])

In [36]:
#proper copy
arr_slice = arr[5:8].copy()
arr_slice[:] = 6
arr
#arr remains same

array([ 0,  1,  2,  3,  4, 65, 65, 65,  8,  9])

In [37]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [38]:
# Thus, individual elements can be accessed recursively. But that is a bit too much
# work, so you can pass a comma-separated list of indices to select individual elements.
# So these are equivalent:
arr2d[0][2]

3

In [39]:
arr2d[0, 2]

3