In [2]:
import numpy as np

In [3]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [4]:
data

array([[ 0.02041102, -0.15090835, -0.11587738, -0.44330309],
       [ 0.24984274,  0.18196663, -0.8599626 ,  2.03621351],
       [-1.02502827, -0.08191543, -0.63430388,  1.1427858 ],
       [-1.22115045,  1.0937459 ,  1.30679622,  0.01076915],
       [-0.0722418 , -1.42001722, -0.0258508 ,  0.59563882],
       [-0.92054207, -0.9724636 , -1.42763667,  0.10385036],
       [ 0.43049441,  0.27664705,  1.58811217,  0.96665057]])

In [6]:
names=="Bob"

array([ True, False, False,  True, False, False, False])

In [7]:
data[names == 'Bob']

array([[ 0.02041102, -0.15090835, -0.11587738, -0.44330309],
       [-1.22115045,  1.0937459 ,  1.30679622,  0.01076915]])

In [9]:
data[names == 'Bob',2:]

array([[-0.11587738, -0.44330309],
       [ 1.30679622,  0.01076915]])

In [10]:
data[names == 'Bob',3]

array([-0.44330309,  0.01076915])

In [15]:
names != 'Bob'
data[names!="Bob"]
#  or alternate form is
data[~(names=="Bob")]

array([[ 0.24984274,  0.18196663, -0.8599626 ,  2.03621351],
       [-1.02502827, -0.08191543, -0.63430388,  1.1427858 ],
       [-0.0722418 , -1.42001722, -0.0258508 ,  0.59563882],
       [-0.92054207, -0.9724636 , -1.42763667,  0.10385036],
       [ 0.43049441,  0.27664705,  1.58811217,  0.96665057]])

In [16]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [18]:
data[data < 0] = 0
data

array([[0.02041102, 0.        , 0.        , 0.        ],
       [0.24984274, 0.18196663, 0.        , 2.03621351],
       [0.        , 0.        , 0.        , 1.1427858 ],
       [0.        , 1.0937459 , 1.30679622, 0.01076915],
       [0.        , 0.        , 0.        , 0.59563882],
       [0.        , 0.        , 0.        , 0.10385036],
       [0.43049441, 0.27664705, 1.58811217, 0.96665057]])

In [19]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.24984274, 0.18196663, 0.        , 2.03621351],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.10385036],
       [0.43049441, 0.27664705, 1.58811217, 0.96665057]])