In [18]:
import numpy as np
data = np.random.randn(2, 3)
data

array([[ 1.04249654,  0.02325691, -0.77596911],
       [-0.67421791, -0.72454955, -0.18258609]])

In [19]:
data = data * 10
data

array([[10.42496538,  0.23256908, -7.75969108],
       [-6.74217914, -7.24549546, -1.82586089]])

In [20]:
data = data+data
data

array([[ 20.84993076,   0.46513816, -15.51938216],
       [-13.48435827, -14.49099092,  -3.65172178]])

In [23]:
data.shape
data.dtype

dtype('float64')

In [40]:
#creating ndArray
data = [1,2,3.5,8.9,7]
arr1 = np.array(data)
#similarly,
data1 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data1)
arr2
arr2.shape
# arr2.ndim

(2, 4)

In [42]:
np.zeros(10)
np.zeros((3,3,3))
np.zeros((3,6))
np.empty((2,3,2))

array([[[7.99537713e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.03977794e-312, 9.13741182e+169]],

       [[5.39652845e-062, 9.13004179e+169],
        [2.96184654e-032, 2.64368934e+180],
        [8.67344568e-067, 5.70093229e-038]]])

In [43]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([1, 2, 3])