In [2]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:

arr * arr


array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [4]:
arr - arr


array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
#Arithmetic operations with scalars propagate the scalar argument to each element in
#the array:
1 / arr
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [6]:
#Comparison; compares corresponding entries
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])